config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from sesame.views import LoginView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("dashboard/", include("moodmusic.dashboard.urls", namespace="dashboard")),
    path("ema/", include("moodmusic.ema.urls")),
    path("", include("social_django.urls", namespace="social")),
    path("login/auth/", LoginView.as_view(), name="login"),
    path("sesame/login/", LoginView.as_view(), name="sesame-login"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

moodmusic/dashboard/urls.py
from django.urls import path
from . import views

app_name = "dashboard"
urlpatterns = [
    path("", view=views.dashboard, name="index"),
    path("thanks/", view=views.thanks, name="thanks"),
    path("spotify-connect/", view=views.spotify, name="spotify"),
    path("data-drop/", views.datadrop, name="datadrop"),
    path("verification/", views.phone_verification, name="phone_verification"),
    path("verification/token/", views.token_validation, name="token_validation"),
    path("verified/", views.verified, name="verified"),
    path("check-email/", views.static.check_email, name="check_email"),
]

moodmusic/ema/urls.py
from django.urls import path
from .views import views

urlpatterns = [
    path("", views.respond_to_incoming_message, name="ema"),
]

moodmusic/dashboard/views.py
import json
from datetime import datetime, timezone
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, FormView
from django.contrib.auth import get_user_model
from phonenumber_field.widgets import PhoneNumberInternationalFallbackWidget

from .twilio_client import verification_checks, verifications
from .forms import TokenForm, UploadListeningHistoryForm
from moodmusic.music.models import FullUserHistory


@login_required
def dashboard(request):
    return render(request, "dashboard/dashboard.html", {})


@login_required
def thanks(request):
    return render(request, "dashboard/thanks.html", {})


@login_required
def spotify(request):
    return render(request, "dashboard/spotify-connect.html", {})


@login_required
def mobile_guide(request):
    return render(request, "dashboard/mobile-surveys.html", {})


class PhoneVerificationView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    fields = ["phone_number"]
    template_name = "dashboard/phone-verification.html"

    def get_form(self, form_class=None):
        form = super(PhoneVerificationView, self).get_form(form_class)
        # This widget defaults to a UK number, unless a country code is specified
        form.fields["phone_number"].widget = PhoneNumberInternationalFallbackWidget()
        return form

    def form_valid(self, form):
        self.request.session["phone_number"] = form.cleaned_data["phone_number"].as_e164
        # Send the phone number to Twilio to generate a verification code
        verifications(form.cleaned_data["phone_number"].as_e164, via="sms")
        return super().form_valid(form)

    def get_object(self, queryset=None):
        # NB this is really important for authorisation!
        # Makes sure that only the logged in user's number is shown.
        return self.request.user

    def get_success_url(self):
        return reverse("dashboard:token_validation")


phone_verification = PhoneVerificationView.as_view()


@login_required
def token_validation(request):
    if request.method == "POST":
        form = TokenForm(request.POST)
        if form.is_valid():
            verification = verification_checks(
                request.session["phone_number"], form.cleaned_data["token"]
            )

            if verification.status == "approved":
                request.session["is_verified"] = True
                # Update user record in the database
                request.user.phone_verified = True
                request.user.save()
                return redirect("dashboard:verified")
            else:
                for error_msg in verification.errors().values():
                    form.add_error(None, error_msg)
    else:
        form = TokenForm()
    return render(request, "dashboard/token-validation.html", {"form": form})


@login_required
def verified(request):
    """View to confirm to user that their number is verified"""
    if not request.session["is_verified"]:
        return redirect("dashboard:phone_verification")
    return render(request, "dashboard/verified.html")


class DataDropView(LoginRequiredMixin, FormView):
    form_class = UploadListeningHistoryForm
    template_name = "dashboard/data-drop.html"
    success_url = reverse_lazy("dashboard:thanks")

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist("file_field")
        if form.is_valid():
            for f in files:
                handle_uploaded_file(f, request.user)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


datadrop = DataDropView.as_view()


def handle_uploaded_file(file, user):
    """For each uploaded JSON file, save the
    fields we are interested in to the database"""
    try:
        history = json.load(file)
    except json.decoder.JSONDecodeError:
        history = json.load(file.decode("utf-8"))
        # Generate all the objects first and then do a
        # bulk save to the database. This avoids too many data-
        # base calls.
    try:
        songs = [
            FullUserHistory(
                user=user,
                end_time=datetime.strptime(song["endTime"], "%Y-%m-%d %H:%M").replace(
                    tzinfo=timezone.utc
                ),
                artist=song["artistName"],
                track_name=song["trackName"],
                ms_played=int(song["msPlayed"]),
            )
            for song in history
        ]

        # Save to database
        FullUserHistory.objects.bulk_create(songs)

    except Exception as e:
        # TODO: Insert logging!
        raise e

moodmusic/dashboard/views/data_drop.py
import json
import os
import logging
from datetime import datetime, timezone
from django.core.exceptions import ValidationError
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import FormView

from moodmusic.dashboard.forms import UploadListeningHistoryForm
from moodmusic.music.models import FullUserHistory

logger = logging.getLogger(__name__)


class DataDropView(LoginRequiredMixin, SuccessMessageMixin, FormView):
    form_class = UploadListeningHistoryForm
    template_name = "dashboard/data-drop.html"
    # success_url = reverse_lazy("dashboard:thanks")
    success_message = "Thank you! Your file/s were sucessfully saved."

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist("file_field")
        if form.is_valid():
            for f in files:
                # First check the file extension
                try:
                    validate_ext(f)
                except ValidationError:
                    messages.add_message(
                        request,
                        messages.WARNING,
                        """Please make sure you are uploading a file ending in .json""",
                    )
                    return self.form_invalid(form)
                # Then try and catch for errors in the json
                try:
                    handle_uploaded_file(f, request.user)
                except ValidationError:
                    messages.add_message(
                        request,
                        messages.WARNING,
                        """Sorry, this document does not contain the expected data.
                        Please check that you are uploading a 'StreamingHistory' file
                         and try again.""",
                    )
                    return self.form_invalid(form)
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_success_url(self):
        """Overwrite success view to remain on the same page"""
        return self.request.path


datadrop = DataDropView.as_view()


def validate_ext(file):
    """Make sure file name passed ends in .json. Raise ValidationError otherwise."""
    ext = os.path.splitext(file.name)[1]
    valid_extensions = [".json"]
    if not ext.lower() in valid_extensions:
        raise ValidationError("Sorry, only .json files are accepted.")


def handle_uploaded_file(file, user):
    """For each uploaded JSON file, save the
    fields we are interested in to the database """

    # Get the file from the InMemoryUploadedObject
    file = file.file

    try:
        history = json.load(file)
    except AttributeError:
        history = json.load(file.decode("utf-8"))

    # Check the file is not empty
    if len(history) == 0:
        raise ValidationError("Empty JSON.")

    # Generate all the objects first and then do a
    # bulk save to the database. This avoids too many data-
    # base calls.
    try:
        songs = [
            FullUserHistory(
                user=user,
                end_time=datetime.strptime(song["endTime"], "%Y-%m-%d %H:%M").replace(
                    tzinfo=timezone.utc  # This converts from naive to timeaware TZ
                ),
                artist=song["artistName"],
                track_name=song["trackName"],
                ms_played=int(song["msPlayed"]),
            )
            for song in history
        ]

        # Save to database
        FullUserHistory.objects.bulk_create(songs)

    except (TypeError, KeyError):
        # These two errors will be raised if the JSON file is not consisten with the
        # format expected.
        raise ValidationError(
            """This is not the expected file format. Please check
    that you are uploading a 'StreamingHistory' file."""
        )
    except Exception as e:
        # TODO logger.exception("File upload was not completed and raised an Exception.")
        raise e

moodmusic/dashboard/views/static.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


def check_email(request):
    return render(request, "dashboard/check-email.html", {})

@login_required
def dashboard(request):
    return render(request, "dashboard/dashboard.html", {})


@login_required
def thanks(request):
    return render(request, "dashboard/thanks.html", {})


@login_required
def spotify(request):
    return render(request, "dashboard/spotify-connect.html", {})


@login_required
def mobile_guide(request):
    return render(request, "dashboard/mobile-surveys.html", {})

moodmusic/dashboard/views/twilio_verify.py
"""Views that control the phone number verification process, using Twilio's Verify API.

These views will request an authentication code from the API for the number the user
provides, and the use the API again the verify that the user provided code is as excepted.

Further documentation about the Verify API is available here: https://www.twilio.com/docs/verify/api.

The file moodmusic/dashboard/twilio_client.py contains the authentication codes for the API calls."""

from django.contrib import messages
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.views.generic.edit import UpdateView
from phonenumber_field.widgets import PhoneNumberInternationalFallbackWidget
from django.http import HttpResponseRedirect

from moodmusic.dashboard.twilio_client import verification_checks, verifications
from moodmusic.dashboard.forms import TokenForm


class PhoneVerificationView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    fields = ["phone_number"]
    template_name = "dashboard/phone-verification.html"

    def get_form(self, form_class=None):
        form = super(PhoneVerificationView, self).get_form(form_class)
        # This widget defaults to a UK number, unless a country code is specified
        form.fields["phone_number"].widget = PhoneNumberInternationalFallbackWidget()
        return form

    def form_valid(self, form):
        self.request.session["phone_number"] = form.cleaned_data["phone_number"].as_e164
        # Send the phone number to Twilio to generate a verification code
        verifications(form.cleaned_data["phone_number"].as_e164, via="sms")
        return super().form_valid(form)

    def get_object(self, queryset=None):
        # NB this is really important for authorisation!
        # Makes sure that only the logged in user's number is shown.
        return self.request.user

    def get_success_url(self):
        return reverse("dashboard:token_validation")


phone_verification = PhoneVerificationView.as_view()


@login_required
def token_validation(request):
    if request.method == "POST":
        form = TokenForm(request.POST)
        if form.is_valid():
            verification = verification_checks(
                request.session["phone_number"], form.cleaned_data["token"]
            )

            if verification.status == "approved":
                request.session["is_verified"] = True
                # Update user record in the database
                request.user.phone_verified = True
                request.user.save()
                return redirect("dashboard:verified")
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    """Sorry, that token was not correct. Please try again, or go back
                        to check your phone number is correct.""",
                )
                HttpResponseRedirect(request.path_info)
    else:
        form = TokenForm()
    return render(request, "dashboard/token-validation.html", {"form": form})


@login_required
def verified(request):
    """View to confirm to user that their number is verified"""
    # If the request doesn't contain the expected payload just redirect
    if "is_verified" in request.session:
        if request.session["is_verified"]:
            return render(request, "dashboard/verified.html")
    else:
        return redirect("dashboard:phone_verification")

moodmusic/ema/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from twilio.twiml.messaging_response import MessagingResponse


@csrf_exempt
def respond_to_incoming_message(request):
    """Responds to a text message to the Twilio number with a predefined message"""
    # Start response
    resp = MessagingResponse()

    # Add a text message to the response
    resp.message("Check out this cute owl! https://bit.ly/3i3ru4p")

    return HttpResponse(str(resp))

moodmusic/ema/views/decorators.py
"""Decorator for the Twilio webhook that validates incoming requests.

Validation is done by comparing the signature from Twilio recieved in the payload
with the known authorisation token for the Twilio account being used.
This will ensure the application will only respond to genuine requests we can be
sure came from Twilio. 
"""

from django.conf import settings
from django.http import HttpResponseForbidden
from functools import wraps
from twilio.request_validator import RequestValidator

import os


def validate_twilio_request(f):
    """Validates that incoming requests genuinely originated from Twilio"""

    @wraps(f)
    def decorated_function(request, *args, **kwargs):
        # Create an instance of the RequestValidator class
        validator = RequestValidator(os.environ.get("TWILIO_AUTH_TOKEN"))

        # Validate the request using its URL, POST data,
        # and X-TWILIO-SIGNATURE header
        request_valid = validator.validate(
            request.build_absolute_uri(),
            request.POST,
            request.META.get("HTTP_X_TWILIO_SIGNATURE", ""),
        )

        # Continue processing the request if it's valid (or if DEBUG is True)
        # and return a 403 error if it's not
        if request_valid or settings.DEBUG:
            return f(request, *args, **kwargs)
        else:
            return HttpResponseForbidden()

    return decorated_function

moodmusic/templates/dashboard/base.html
{% extends "base.html" %}
{% block title %}{% block head_title %}{% endblock head_title %}{% endblock title %}

{% block content %}
  <div class="row">
    <div class="col-md-8 offset-md-3">
      {% block inner %}{% endblock %}
    </div>
  </div>
{% endblock %}

moodmusic/templates/dashboard/check-email.html
{% extends "account/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Verify Your E-mail Address" %}{% endblock %}

{% block inner %}
    <h1>{% trans "Check your email" %}</h1>

    <p>{% blocktrans %}We have sent you an email - please follow the one-time link provided to complete the study sign up process.</p>
    <p>Contact Nina on nina.dicara@bristol.ac.uk if you do not receive your email, and remember to check your spam box in case!{% endblocktrans %}</p>

{% endblock %}

moodmusic/templates/dashboard/consent-form.html
{% extends "dashboard/base.html" %}
{% block title %}{% block head_title %}Dashboard{% endblock head_title %}{% endblock title %}

{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Yes I consent to take part in this study">
</form>

{% endblock %}

moodmusic/templates/dashboard/dashboard.html
{% extends "dashboard/base.html" %}
{% block title %}{% block head_title %}Dashboard{% endblock head_title %}{% endblock title %}

{% block content %}

  <div class="container-fluid">
    <h1>Welcome to the Mood Music study!</h1>
  
    <p>There are three steps for you to complete today:</p>
    <li>Step 1: Add your phone number so that you can recieve your text surveys.</li>
    <li>Step 2: Connect your Spotify account so that we can access your listened songs.</li>
    <li>Step 3: Complete some information about yourself.</li>

    <br>
    <p>Please complete these steps in one go if possible. It should take up to 30 minutes. </p>
    <p>Remember, if you have any questions then you can contact <a href="mailto:nina.dicara@bristol.ac.uk">Nina Di Cara</a> on nina.dicara@bristol.ac.uk</p>


    <a href="{% url 'dashboard:phone_verification' %}" class="btn btn-primary" role="button">Step 1: Add my phone number</a>

  </div>

{% endblock %}

moodmusic/templates/dashboard/data-drop.html
{% extends "dashboard/base.html" %}
{% load crispy_forms_tags %}

{% block title %}{% block head_title %}Dashboard{% endblock head_title %}{% endblock title %}

{% block content %}

<h3>How to request your personal data from Spotify</h3>

<p>Spotify allows you to download your personal user data from the 'Privacy Settings' section of your 
    Spotify account. Here is how to request it: </p>
    
    <ol>
        <li>Go to <a href="https://www.spotify.com/us/account/privacy/" target="_blank">www.spotify.com/us/account/privacy/</a>. 
            You might need to log in.</li>
        <li>Go to the bottom of the page to a section called 'Download My Data'.</li>
        <li>If you follow the instructions then Spotify will email you a link to download
            you data. This usually happens within 24 hours.</li>
        <li>Once you have recieved your data, come back here and use the box below to upload it.</li>
    </ol>

<h3>Upload your listening data</h3>

<p> You will have had several files sent to you. The ones you need to upload will be called <strong>StreamingHistory.json</strong>.
    These contain a record of all the songs you have listened to. There might be several of these files which are numbered, please 
    upload them all.
</p>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.non_field_errors }}
    {{ form.file_field.errors}}

    {{ form | crispy }}

    <input type="submit" value="Upload my files" id="datadrop-btn">
</form>


{% endblock %}

moodmusic/templates/dashboard/phone-verification.html
{% extends "dashboard/base.html" %}
{% block title %}{% block head_title %}Dashboard{% endblock head_title %}{% endblock title %}

{% block content %}

<h2>Step 1: Add your phone number</h2>

<div class="modal-body row">
    <div class="col-md-6">
        <p>Provide the phone number below that you would like to receive your daily surveys on.
            The surveys will be sent over text message by our automated system.</p>            
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Verify my phone number" class="btn btn-success">
            </form>
        <p>If you have a non-UK phone number then include the country code after a "+" sign.</p>

    </div>
    <div class="col-md-6">
        <h3>Phone safety tips</h3>
        <p>We will be keeping the responses that you send us secure, but here are some tips to keep the message history on your phone secure too.
            <ol>
                <li>Make sure that your phone has a <b>passcode</b> so that other people cannot access your data.</li>
                <li>If you wish you can <b>delete the messages</b> after you have sent your replies. This will not affect our copy of the 
                    data and will only delete the history from your phone.</li>
            </ol></p>
    </div>
  </div>
  





        

{% endblock %}

moodmusic/templates/dashboard/spotify-connect.html
{% extends "dashboard/base.html" %}

{% block title %}{% block head_title %}Connect Spotify{% endblock head_title %}{% endblock title %}

{% block content %}
    

    <h2>Step 2: Connect your Spotify account</h2>

    <li>When you click below you will be taken to Spotify's website and will have to log in.</li>
    <li>The website will tell you what data you are consenting to share with us before you confirm it. </li>
        

    <a href="{% url 'social:begin' 'spotify' %}" class="btn btn-success" role="button">Authorise access to my Spotify listening data</a>

{% endblock content %}

moodmusic/templates/dashboard/thanks.html
{% extends "dashboard/base.html" %}

{% block title %}{% block head_title %}Success{% endblock head_title %}{% endblock title %}

{% block content %}

    <h2>Success!</h2>
    
    <p>Thanks, your Spotify account is now connected.</p>

    <p>The last thing we need from you today is to complete some surveys about yourself and your mental health and well-being. 
        The button below will take you to an online survey.
    </p>

    <a href="{% url 'dashboard:index' %}" class="btn btn-primary" role="button">Step 3: About me</a>


{% endblock content %}

moodmusic/templates/dashboard/token-validation.html
{% extends "base.html" %}

{% block content %}

{% block container %}
  <form role="form" method="POST">
    {% csrf_token %}

    {{ form.non_field_errors }}
    {{ form.token.errors}}

    {{ form.token }}
    <input type="submit" value="Verify Phone" class="btn btn-info">
  </form>

  <a href="{% url 'dashboard:phone_verification' %}" class="btn btn-secondary" role="button">Go back and change my phone number</a>

{% endblock %}

{% endblock %}

moodmusic/templates/dashboard/verified.html
{% extends "base.html" %}

{% block content %}

{% block container %}
<div class="row centered-form">
  <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Success!</h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <p>
              Your phone number is verified. Thank you! 
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12">
          </div>
        </div>
        <a href="{% url 'dashboard:spotify' %}" class="btn btn-primary" role="button">Step 2: Connect my Spotify account</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% endblock %}